#ifndef AEDS2_APLICACAO_ARVORE_B_DISKRW_H
#define AEDS2_APLICACAO_ARVORE_B_DISKRW_H

void STATS_RESET();
void STATS_PRINT();
void STATS_DISKREAD();
void STATS_DISKWRITE();
void STATS_COMPARISON();

#endif //AEDS2_APLICACAO_ARVORE_B_DISKRW_H
